name: app_with_bloc
description: "Stopwatch app with precise time tracking, lap saving, and
  customizable themes."

publish_to: 'none'

version: 1.0.9+10

environment:
  sdk: ^3.5.1

dependencies:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  meta: ^1.15.0
  mockito: ^5.4.4
  path_provider: ^2.1.4
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  test: ^1.25.7
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/stopwatch.png"

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml